spring.application.name=SecureDocumentVault
spring.main.banner-mode=off
logging.level.root=warn
logging.level.org.springframework.security=DEBUG

# MongoDB connection
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=securedocumentvault
spring.data.mongodb.auto-index-creation=true

# File upload
spring.servlet.multipart.max-file-size=256MB
spring.servlet.multipart.max-request-size=256MB
spring.servlet.multipart.enabled=true

# Enable all endpoints for actuator
management.endpoints.web.exposure.include=*

# ------------ Usefull actuator endpoints ------------
# /beans: returns all available beans in our BeanFactory
# /env: returns current environment properties
# /health: summarizes the health status of our application
# /metrics: details metrics of our application
# /loggers: enables us to query and modify the logging level of our application
# /threaddump: dumps the thread information of the underlying JVM
