# spring settings
spring.application.name=SpringVault
logging.level.org.springframework.security=DEBUG
logging.level.root=warn

# database settings
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# file storage
spring.servlet.multipart.max-file-size=256MB
spring.servlet.multipart.max-request-size=256MB
spring.servlet.multipart.enabled=true

# actuator settings
management.endpoints.web.exposure.exclude=*
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
